import Cabecalho from "@/components/Cabecalho/cabecalho"
import Rodape from "@/components/Rodape/rodape"
import './global.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })




export const metadata = {
  title: 'Auto-Cara',
  description: 'Generated by J.A.R.V.I.S',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Cabecalho/>
        
        {children}</body>

        <Rodape/>
    </html>
  )
}
